# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_person_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.DateField(auto_now=True),
        ),
    ]
