# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_person_joining_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='dob',
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
