# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20170607_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='graduated',
            field=models.NullBooleanField(),
        ),
    ]
