# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_person_graduated'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='year',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='first', max_length=30),
        ),
    ]
