# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20170607_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='roll_no',
            field=models.IntegerField(default=123, primary_key=True, serialize=False),
        ),
    ]
