# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20170607_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('time', models.TimeField()),
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
