# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='class_room_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.ClassRoom'),
        ),
    ]
