# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.FileField(default='demo.jpg', upload_to='pictures'),
            preserve_default=False,
        ),
    ]
